-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.combined_table
(
    emp_no integer,
    birth_date date,
    first_name text COLLATE pg_catalog."default",
    last_name text COLLATE pg_catalog."default",
    sex character varying(255) COLLATE pg_catalog."default",
    hire_date date,
    department_no character varying(255) COLLATE pg_catalog."default",
    department_name text COLLATE pg_catalog."default",
    salary integer,
    emp_title_id character varying(255) COLLATE pg_catalog."default",
    title text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.departments
(
    dept_no character varying(255) COLLATE pg_catalog."default" NOT NULL,
    dept_name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_departments PRIMARY KEY (dept_no)
);

CREATE TABLE IF NOT EXISTS public.dept_emp
(
    emp_no integer NOT NULL,
    dept_no character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dept_emp_pkey PRIMARY KEY (emp_no)
);

CREATE TABLE IF NOT EXISTS public.dept_manager
(
    dept_no character varying(255) COLLATE pg_catalog."default" NOT NULL,
    emp_no integer NOT NULL,
    CONSTRAINT pk_dept_manager PRIMARY KEY (dept_no, emp_no)
);

CREATE TABLE IF NOT EXISTS public.employees
(
    emp_no integer NOT NULL,
    emp_title_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    birth_date date NOT NULL,
    first_name text COLLATE pg_catalog."default" NOT NULL,
    last_name text COLLATE pg_catalog."default" NOT NULL,
    sex character varying(255) COLLATE pg_catalog."default" NOT NULL,
    hire_date date NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (emp_no)
);

CREATE TABLE IF NOT EXISTS public.salaries
(
    emp_no integer NOT NULL,
    salary integer NOT NULL,
    CONSTRAINT pk_salaries PRIMARY KEY (emp_no)
);

CREATE TABLE IF NOT EXISTS public.titles
(
    emp_title_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_titles PRIMARY KEY (emp_title_id)
);
END;